name: dart_playground
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.3

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  at_client: ^3.0.75
  at_onboarding_cli: ^1.4.3
  at_utils: ^3.0.16
  version: ^3.0.2
  crypto: ^3.0.3
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
